import { test } from "vitest";
import request from "@/fetch";

test("Request testing", () => {
  // Этот тест проходит, потому что он не выбрасывает исключение.
});
